--- 
global: 
  owner: aec@acqueon.com
  qsname: aec-modules
  regions: 
    - us-east-2
    - us-east-1
    - us-west-2
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - eu-west-3
    - sa-east-1
  reporting: true
tests: 
  aec-txl: 
    regions:
      - us-east-1
    parameter_input: txl-input.json
    template_file: aec-master.template
